apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://api.kube.example.com:6443
    proxy-url: https://localhost:8090
  name: example
contexts:
- context:
    cluster: example
    namespace: default
    user: admin@example
  name: admin@example
users:
- name: admin@example
  user:
    username: anon
current-context: admin@example
